
version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - /var/lib/postgres
    environment:
      MYSQL_DATABASE: qp
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: qp
  # APP  ***************************************************************************************
  grocery-app:
    image: hub.docker.com/grocery-app:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect
      spring.jpa.hibernate.ddl-auto : create-drop
      spring.jpa.hibernate.show-sql: true
      spring.datasource.url : jdbc:postgresql://localhost:5432/qp
      spring.datasource.username : postgres
      spring.datasource.password : root
    restart: on-failure
    depends_on:
      - mariadb
volumes:
  postgres:
